#!/bin/bash

curl -X PUT -d '{"Red Eared Slider": {"name": "Red Eared Slider", "class": "Pond Turtle", "description": "Red-eared sliders are strong swimmers and will spend a majority of their time in the water. They bask a lot, too, and during warm, sunny days, wild red-ears love to stack on top of each other while doing so.", "url": "https://canalrivertrust.org.uk/refresh/media/original/21587.jpg?v=785f1a", "favorite": "true"}}' 'https://angular-turts.firebaseio.com/turtles.json'

curl -X PATCH -d '{"Gulf Coast Box Turtle": {"name": "Gulf Coast Box Turtle", "class": "Box Turtle", "description": "Of all the sub-species of box turtle, the gulf coast box turtle is the largest. They have a large dome shell. Their skin and shell is often dark colored, such as browns and blacks.", "url": "https://upload.wikimedia.org/wikipedia/commons/d/d6/Terrapene_carolina_major_2.jpg", "favorite": "false"}}' 'https://angular-turts.firebaseio.com/turtles.json'

curl -X PATCH -d '{"Alligator Snapping Turtle": {"name": "Alligator Snapping Turtle", "class": "Snapping Turtle", "description": "The alligator snapping turtle is characterized by a large, heavy head, and a long, thick shell with three dorsal ridges of large scales, giving it a primitive appearance reminiscent of some of the plated dinosaurs.", "url": "https://upload.wikimedia.org/wikipedia/commons/8/88/Alligator_snapping_turtle.jpg", "favorite": "false"}}' 'https://angular-turts.firebaseio.com/turtles.json'

curl -X PATCH -d '{"Loggerhead Sea Turtle": {"name": "Loggerhead Sea Turtle", "class": "Sea Turtle", "description": "The loggerhead sea turtle is the world'"'"'s largest hard-shelled turtle, slightly larger at average and maximum mature weights than the green sea turtle and the Galapagos tortoise.", "url": "http://www.nwf.org/-/media/NEW-WEBSITE/Shared-Folder/Wildlife/Reptiles/reptile_loggerhead-sea-turtle_600x300.ashx", "favorite": "true"}}' 'https://angular-turts.firebaseio.com/turtles.json'

curl -X PATCH -d '{"Donatello": {"name": "Donatello", "class": "Teenage Mutant Ninja", "description": "Brainy, yet approachable.", "url": "https://static.comicvine.com/uploads/original/3/30334/2521018-turtle1394.jpg", "favorite": "true"}}' 'https://angular-turts.firebaseio.com/turtles.json'
